import Image from "next/image"
import logo from 'assets/ICSCCAT logo.png'
export default function Head() {
  return (
    <>
      <title>ICSCCAT 2024</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
