import nitdAdmin from '@/public/nitd_admin.jpg'
import nitdAcad from '@/public/nitd_acad.jpg'
import du from '@/public/du.jpg'
import ssdu from '@/public/Swami Shraddhanand College 1.jpg'

export const aboutColleges = {
    nitd: {
        heading1: "About National Institute of Technology, Delhi",
        text1: "National Institute of Technology Delhi (NITD) is one of the thirty NIT(s) established in the year 2010 by an act of the parliament and has been declared as an Institute of National importance. NIT Delhi is an autonomous Institute, which functions under the aegis of the Ministry of Education, Government of India. It aims to provide education and research facilities in various disciplines of Engineering, Science and Technology, Management, Social Sciences, and Humanities for advanced learning and dissemination of knowledge. The mission of NIT Delhi is to develop a highly intelligent and deeply ethical human resource, a workforce which is creative, competitive and innovative. The Institute is imparting holistic education, along with inculcating high moral values in its students.",
        image1: nitdAdmin,
        text2: "NIT Delhi started its academic session in 2010 and it was operating from its transit campus at Narela, Delhi until recently. The institute has now completely shifted to its permanent campus situated on NH-1 (GT Karnal Road), Narela sub-city, New Delhi. The institute offers B. Tech. programmes in three areas of technology (Computer Science and Engineering, Electronics and Communication Engineering, and Electrical Engineering), M. Tech. programmes in five disciplines, along with Ph.D. programmes in all branches of Science and Engineering. The institute is all set to start B. Tech. programmes in two new branches (Mechanical Engineering and Civil Engineering) from academic session 2022-23.",
        image2: nitdAcad,
        text3: "The institute makes all attempts to establish strong research collaborations in evolving fields of research in science and engineering. The programmes like joint thesis work, inter-institute collaborative projects, institute assistantship to PG and doctoral students, and administrative support to faculty members for taking up research and consultancy work (sponsored by external agencies). From 2022-23 academic session, the institute has started the Post-Doctoral Fellowship (PDF) programme to further escalate the research activities. NIT Delhi has implemented the guidelines of National Education Policy (NEP) 2020 for current batches of students.",
        heading2: "About Department of Applied Sciences NIT Delhi",
        text4: "The Department of Applied Sciences provides an inclusive environment by integrating a range of educational, research and consultancy opportunities to enhance knowledge and skills. The department acts as a bridge between the basic sciences like physics, chemistry and mathematics with engineering procedures. Faculty in applied sciences is involved in teaching high quality basic and advanced courses to the undergraduate students to make them strong in fundamentals related to their concerned engineering disciplines. Also, our faculty provides the graduate students with knowledge and skills by offering specialized courses across a broad range of study options in M. Tech. and Doctoral programmes. The department has its own doctoral programme in applied physics, chemistry, and pure and applied mathematics. The department aspires to develop the full potential of our students whilst offering an enriched educational experience that equips them with the qualifications and skills to achieve their scientific and technical ambitions.The department has several specialized research laboratories, and is all set to start M. Tech. programmes in \"Smart Materials and Technology\" and \"Mathematics and Computation\"."
    },
    ssdu: {
        heading1: "About Swami Shraddhanand College, University of Delhi",
        text1: "",
        image1: du,
        text2: "The University of Delhi is a premier university of the country with a venerable legacy and international acclaim for highest academic standards, diverse educational programmes, distinguished faculty, illustrious alumni, varied co-curricular activities and modern infrastructure. Over the many years of its existence, the University has sustained the highest global standards and best practices in higher education. It has long-term commitment to nation building and unflinching adherence to universal human values. Beginning with three colleges and 750 students, it has grown as one of the largest universities in India with over 80 academic departments, an equal number of colleges and over seven lakh students. Over 500 programmes offered by the University are approved by Academic and Executive Councils, out of which 209 programmes are being considered for NAAC accreditation purpose. The rest being run in colleges are separately accredited. Moreover, five departments namely Chemistry, Geology, Zoology, Sociology and History have been awarded the status of the Centres of Advanced Studies. These Centres of Advanced Studies have carved a niche for themselves as centres of excellence in teaching and research in their respective areas.",
        image2: ssdu,
        text3: "Swami Sharddhanand College, a constituent College of Delhi University, is run under the trusteeship of Delhi Govt. It is a co-educational institution. Situated in the sylvan ambience o North Delhi, the College has completed 54 years of its existence. From the humble beginning in the Gandhi Ashram building in Narela, the college is now one of the premier institutions o Delhi University. College has made rapid strides in terms of both the strength and infrastructure. The new campus of the college is situated in an area of ten acres in a serene green environment on the National Highway at Alipur, Delhi. It is equipped with qualified teaching and non-teaching staff, specialized science, computer and research laboratories adequate library facilities, well-maintained lawns and play ground. The college has a huge team of dedicated faculty members to impart education in many subjects including Physics Chemistry, Botany, Zoology, Microbiology, Mathematics, English, Hindi, Sanskrit, Commerce, Economics, History, Geography, Political Science, Physical Education an OMSP for a total projected student strength of 3978. The college is committed to provide quality education to the student community at both undergraduate and postgraduate levels. A college, emphasis is given not only to make students academically brilliant, but also to imbibe the essence of value system, character building, socio-ethical responsibilities an dedication towards work. It attempts to provide an integrated and multi-disciplinary education that can help students to discover their true potential.",
        heading2: "About Department of Chemistry, SSNC",
        text4: "The Department of Chemistry, SSNC is one of the esteemed departments of the college. It was established in 1967. The Department offers a B.Sc. Hons. and B.Sc. Program degrees. I offers several core and elective courses. In addition, skill enhancement and value addition courses are also offered by the department. The Department of Chemistry has a dedicate team of eighteen highly qualified academicians. Apart from the classroom teaching, the faculty members are also actively involved in research and publishing books. Some of th faculty members of the department are very well-known authors as well. Department also has a team of equally diligent laboratory staff. The department has five well-equippe laboratories along with an instrumentation laboratory that houses various modern instruments, such as UV-Visible Spectrophotometer, Flame Photometers, Potentiometers, p meters and colorimeters, etc. The department is keen in adapting new innovation techniques in learning and encourages students to take active part in research."
    }
}