import nitdAdmin from '@/public/nitd_admin.jpg'
import nitdAcad from '@/public/nitd_acad.jpg'


export const aboutColleges = {
    nitd: {
        heading1: "About National Institute of Technology, Delhi",
        text1: "National Institute of Technology Delhi (NITD) is one of the thirty NIT(s) established in the year 2010 by an act of the parliament and has been declared as an Institute of National importance. NIT Delhi is an autonomous Institute, which functions under the aegis of the Ministry of Education, Government of India. It aims to provide education and research facilities in various disciplines of Engineering, Science and Technology, Management, Social Sciences, and Humanities for advanced learning and dissemination of knowledge. The mission of NIT Delhi is to develop a highly intelligent and deeply ethical human resource, a workforce which is creative, competitive and innovative. The Institute is imparting holistic education, along with inculcating high moral values in its students.",
        image1: nitdAdmin,
        text2: "NIT Delhi started its academic session in 2010 and it was operating from its transit campus at Narela, Delhi until recently. The institute has now completely shifted to its permanent campus situated on NH-1 (GT Karnal Road), Narela sub-city, New Delhi. The institute offers B. Tech. programmes in three areas of technology (Computer Science and Engineering, Electronics and Communication Engineering, and Electrical Engineering), M. Tech. programmes in five disciplines, along with Ph.D. programmes in all branches of Science and Engineering. The institute is all set to start B. Tech. programmes in two new branches (Mechanical Engineering and Civil Engineering) from academic session 2022-23.",
        image2: nitdAcad,
        text3: "The institute makes all attempts to establish strong research collaborations in evolving fields of research in science and engineering. The programmes like joint thesis work, inter-institute collaborative projects, institute assistantship to PG and doctoral students, and administrative support to faculty members for taking up research and consultancy work (sponsored by external agencies). From 2022-23 academic session, the institute has started the Post-Doctoral Fellowship (PDF) programme to further escalate the research activities. NIT Delhi has implemented the guidelines of National Education Policy (NEP) 2020 for current batches of students.",
        //heading2: "About Department of Computer Science And Engineering, NIT Delhi",
        //text4: "The Department of Applied Sciences provides an inclusive environment by integrating a range of educational, research and consultancy opportunities to enhance knowledge and skills. The department acts as a bridge between the basic sciences like physics, chemistry and mathematics with engineering procedures. Faculty in applied sciences is involved in teaching high quality basic and advanced courses to the undergraduate students to make them strong in fundamentals related to their concerned engineering disciplines. Also, our faculty provides the graduate students with knowledge and skills by offering specialized courses across a broad range of study options in M. Tech. and Doctoral programmes. The department has its own doctoral programme in applied physics, chemistry, and pure and applied mathematics. The department aspires to develop the full potential of our students whilst offering an enriched educational experience that equips them with the qualifications and skills to achieve their scientific and technical ambitions.The department has several specialized research laboratories, and is all set to start M. Tech. programmes in \"Smart Materials and Technology\" and \"Mathematics and Computation\"."
    },
    
}